version: '3.8'

services:
  networkmanager:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: networkmanager
    network_mode: "host"
    volumes:
      - ./app:/app
      - /app/node_modules
    restart: unless-stopped
