version: '3.8'

services:
  logmanager:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: logmanager
    network_mode: "host"
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/ui/node_modules
    restart: unless-stopped
